# Generated by Django 5.1.4 on 2025-11-07 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('puuid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.CharField(max_length=255)),
                ('player_game_score', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lolers_app.players')),
            ],
        ),
    ]
