# Generated by Django 5.1.4 on 2024-12-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('puuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('rank', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.CharField(max_length=255)),
                ('game_mode', models.CharField(max_length=255)),
                ('player_data', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lolers_app.players')),
            ],
        ),
    ]
